name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - uses: actions/checkout@v3
      - uses: cli/gh-extension-precompile@v1
